spring:
  h2:
    console:
      path: /console2
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/site;DATABASE_TO_UPPER=false
    username: mazo
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl