INSERT INTO Users (email)
VALUES ('aiden.martell93@yahoo.com'),
       ('brianna.keller52@outlook.com'),
       ('cameron.hunt76@gmail.com'),
       ('delilah.frost89@icloud.com'),
       ('elijah.brown34@live.com'),
       ('fiona.steele88@protonmail.com'),
       ('grayson.james22@zoho.com'),
       ('hannah.jameson11@aol.com'),
       ('isaac.reed47@gmail.com'),
       ('julia.cameron55@yahoo.com'),
       ('kyle.turner31@aol.com'),
       ('lily.murphy77@outlook.com'),
       ('mason.collins89@icloud.com'),
       ('nora.dunn30@protonmail.com'),
       ('oliver.miles44@gmail.com'),
       ('piper.clark23@live.com'),
       ('quinn.morris98@zoho.com'),
       ('riley.barnes67@yahoo.com'),
       ('sophie.wilson11@gmail.com'),
       ('toby.russell82@outlook.com');

INSERT INTO Role (name)
VALUES ('Admin'),
       ('Editor'),
       ('Writer'),
       ('Guest'),
       ('Contributor'),
       ('Moderator'),
       ('Researcher'),
       ('Reviewer'),
       ('Lead Writer'),
       ('Junior Writer'),
       ('Project Manager'),
       ('Intern'),
       ('Data Analyst'),
       ('Photographer'),
       ('Editor-in-Chief'),
       ('Columnist'),
       ('Social Media Manager'),
       ('Content Strategist'),
       ('Community Manager'),
       ('Jr. Editor');

INSERT INTO Blog (name, manager_id)
VALUES ('NBA News', 1),
       ('Hoops Central', 2),
       ('Basketball Insights', 3),
       ('Dunk Zone', 4),
       ('Fast Break Updates', 5),
       ('Game Time', 6),
       ('Slam Dunk Nation', 7),
       ('Basketball Daily', 8),
       ('NBA Analysis', 9),
       ('Hoop Dreams', 10),
       ('Full Court Press', 11),
       ('Backcourt Buzz', 12),
       ('Rim Rewind', 13),
       ('Clutch Time Chronicles', 14),
       ('Final Buzzer', 15),
       ('The Basketball Review', 16),
       ('Hoops Hustle', 17),
       ('Court Vision', 18),
       ('Above the Rim', 19),
       ('EuroLeague Final4S', 20);

INSERT INTO Article (title, author_id, blog_id)
VALUES ('The Lakers’ Roller Coaster Season: From Struggles to Triumph', 1, 1),
       ('Why Luka Dončić Could Be the MVP This Year', 2, 1),
       ('Jayson Tatum: A Superstar on the Rise', 3, 2),
       ('Is The Brooklyn Nets’ Rebuild Finally Paying Off?', 4, 2),
       ('The Golden State Warriors: A Dynasty in Transition', 5, 3),
       ('Giannis Antetokounmpo: Still Dominating the East', 6, 3),
       ('The Rise of the Young Kings: Sacramento’s Future', 7, 4),
       ('Why Damian Lillard Still Deserves to Be an MVP Contender', 8, 4),
       ('The Celtics’ Playoff Push: Can They Finish the Job?', 9, 5),
       ('Can the Suns Make It to the Finals This Year?', 10, 5),
       ('The Warriors vs. Lakers: Who’s Really Better This Season?', 1, 1),
       ('Kevin Durant’s Impact on the Phoenix Suns', 2, 2),
       ('Miami Heat’s Secret Weapon: Jimmy Butler’s Leadership', 3, 3),
       ('The Dallas Mavericks’ Big Gamble with Kyrie Irving', 4, 4),
       ('What the NBA Can Learn from the International Growth of Basketball', 5, 5),
       ('Zion Williamson: A Breakout Year?', 6, 1),
       ('Why The Bucks Are Still the Team to Beat in the East', 7, 2),
       ('The Battle for the West: Who Will Come Out on Top?', 8, 3),
       ('The Best Rookies to Watch in 2024-2025', 9, 4),
       ('How the New Rules Are Affecting the NBA Game', 10, 5),
       ('LeBron James: The King’s Legacy in the NBA', 11, 16),
       ('The Evolution of the Three-Point Shot in Modern Basketball', 12, 7),
       ('Are the Clippers Finally Ready for a Championship Run?', 13, 18),
       ('Joel Embiid vs. Nikola Jokić: The Battle of the Bigs', 14, 19),
       ('Steph Curry’s Influence on the Next Generation', 15, 10),
       ('Analyzing the Defensive Impact of Rudy Gobert', 16, 11),
       ('How the NBA’s Pace-and-Space Revolution Changed the Game', 17, 12),
       ('Is Victor Wembanyama the Next NBA Superstar?', 18, 13),
       ('The Importance of a Sixth Man in Championship Teams', 19, 14),
       ('How Analytics is Shaping NBA Strategy', 20, 15),
       ('The NBA’s International Expansion: What’s Next?', 11, 16),
       ('Why Team Chemistry is More Important Than Superstars', 12, 17),
       ('The Most Exciting Dunkers in NBA History', 13, 18),
       ('NBA Free Agency: The Biggest Moves This Offseason', 14, 19),
       ('The Legacy of Kobe Bryant and His Impact on the Game', 15, 11),
       ('Load Management: Does It Really Benefit Players?', 16, 12),
       ('Are the New York Knicks Finally Contenders Again?', 17, 13),
       ('The NBA’s Greatest Rivalries of All Time', 18, 14),
       ('How Player Development Has Evolved Over the Years', 19, 15),
       ('The Future of the NBA: What Rule Changes Could Come Next?', 20, 20);

INSERT INTO User_Role (user_id, role_id)
VALUES (1, 1),
       (2, 2),
       (2, 4),
       (3, 3),
       (4, 4),
       (5, 5),
       (6, 6),
       (7, 7),
       (7, 6),
       (8, 8),
       (9, 9),
       (10, 10),
       (11, 11),
       (12, 12),
       (13, 13),
       (14, 14),
       (14, 1),
       (15, 15),
       (16, 16),
       (17, 17),
       (18, 18),
       (19, 19),
       (19, 9),
       (20, 20);
